networkmap:	main	flat	apartment build

main:
	g++	-std=gnu++11	-c	-g	main.cpp	-o	main.o
flat:
	g++	-std=gnu++11	-c	-g	flat.cpp -o flat.o
apartment:
	g++	-std=gnu++11	-c	-g	apartment.cpp	-o	apartment.o
build:
	g++	-std=gnu++11	main.o	flat.o	apartment.o	-o networkmap