Assignment3:	main	Time	Event	Cashier	Barista	build

main:
	g++	-std=gnu++11	-c	-g	main.cpp	-o	main.o
Time:
	g++	-std=gnu++11	-c	-g	Time.cpp	-o	Time.o
Event:
	g++	-std=gnu++11	-c	-g	Event.cpp	-o	Event.o
Cashier:
	g++	-std=gnu++11	-c	-g	Cashier.cpp -o Cashier.o
Barista:
	g++	-std=gnu++11	-c	-g	Barista.cpp	-o	Barista.o
build:
	g++	main.o	Time.o	Event.o	Cashier.o	Barista.o	-o Assignment3
